[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

[features]
# Show the prompt playground
prompt_playground = true

# Process and display HTML in messages. This can be a security risk
unsafe_allow_html = false

# Process and display mathematical expressions
latex = false

# Automatically tag threads when a user takes an action
auto_tag_thread = true

[UI]
# Name of the app and chatbot.
name = "AutoWriter"

# Show the readme while the thread is empty.
show_readme_as_default = true

# Description of the app and chatbot.
description = "AutoWriter - 智能写作助手，支持多项目管理和智能对话"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

[UI.theme]
default_mode = "dark"

[meta]
generated_by = "1.0.0"