# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "qwen-max-latest"  # or gpt-3.5-turbo
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"  # or forward url / other llm url
  api_key: "sk-e55893a30fad4a2a9e43f20b8eb44efc"

# RAG Embedding - 阿里云DashScope嵌入模型配置
embedding:
  api_type: "openai"  # 兼容OpenAI API格式
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  api_key: "sk-e55893a30fad4a2a9e43f20b8eb44efc"
  model: "text-embedding-v3"  # 阿里云官方模型名称，v3更稳定
  dimensions: 1024  # 输出向量维度

# 知识图谱构建模型 - 快速低成本模型
knowledge_graph:
  api_type: "openai"  # 兼容OpenAI API格式
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  api_key: "sk-e55893a30fad4a2a9e43f20b8eb44efc"
  model: "qwen-flash"  # 快速低成本的图谱构建专用模型

# 阿里云OpenSearch搜索引擎配置
search:
  api_type: "alibaba"  # 改为 alibaba，而不是 custom
  api_key: "OS-ykkz87t4q83335yl"
  endpoint: "http://default-0t01.platform-cn-shanghai.opensearch.aliyuncs.com"
  workspace: "default"
  service_id: "ops-web-search-001"
