# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "qwen-max-latest"  # or gpt-3.5-turbo
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"  # or forward url / other llm url
  api_key: "sk-e55893a30fad4a2a9e43f20b8eb44efc"

# 阿里云OpenSearch搜索引擎配置
search:
  api_type: "alibaba"  # 改为 alibaba，而不是 custom
  api_key: "OS-ykkz87t4q83335yl"
  endpoint: "http://default-0t01.platform-cn-shanghai.opensearch.aliyuncs.com"
  workspace: "default"
  service_id: "ops-web-search-001"
