# =============================================================================
# 绩效分析报告业务配置文件
# 通过修改此文件可以驱动整个业务流程，无需修改代码
# =============================================================================

# 领域基本信息
domain_info:
  name: "绩效分析报告"
  description: "财政项目绩效评价报告生成系统"
  version: "1.0.0"

# =============================================================================
# 知识图谱领域配置 - 用于知识图谱构建和推理
# =============================================================================
knowledge_graph:
  # 实体类型定义
  entity_types:
    项目:
      - "项目名称"
      - "项目类型"
      - "实施地点"
      - "资金规模"
    指标体系:
      - "决策指标"
      - "过程指标"
      - "产出指标"
      - "效益指标"
    具体指标:
      - "指标名称"
      - "计算方法"
      - "目标值"
      - "权重"
    政策法规:
      - "法规名称"
      - "适用范围"
      - "发布机构"
      - "生效时间"
    最佳实践:
      - "实践名称"
      - "适用场景"
      - "实施要点"
      - "预期效果"
    问题案例:
      - "问题类型"
      - "原因分析"
      - "解决方案"
      - "改进建议"
    行业类型:
      - "基础设施"
      - "公益事业"
      - "民生保障"
      - "环境治理"
  
  # 关系类型定义
  relation_types:
    - "包含"
    - "属于"
    - "适用于"
    - "遵循"
    - "参考"
    - "导致"
    - "解决"
    - "改进"
    - "关联"
    - "影响"

# =============================================================================
# 报告结构配置 - 用于架构师设计报告结构
# =============================================================================
report_structure:
  # 标准章节配置
  sections:
    - title: "一、项目概述"
      key: "overview"
      prompt_template: |
        请围绕以下方面详细描述项目概况：
        1. 项目立项背景及目的、项目主要内容
        2. 资金投入和使用情况、项目实施情况
        3. 项目组织管理
        4. 项目绩效目标：通过知识库搜索绩效目标表复制相关内容，务必以表格形式展示项目绩效指标
      keywords:
        - "项目背景与目标"
        - "资金与预算"
        - "实施方案"
        - "效果与成效"
    
    - title: "二、综合绩效评价结论"
      key: "conclusion"
      prompt_template: |
        请基于对项目决策、过程、产出和效益四个维度的全面绩效分析，给出项目的综合评价结论。
        应包含项目总得分、评价等级，并务必以表格形式清晰展示各一级指标（决策、过程、产出、效益）的计划分值、实际得分和得分率
      keywords:
        - "效果与成效"
        - "评价指标"
        - "绩效得分"
    
    - title: "三、主要成效及经验"
      key: "achievements"
      prompt_template: |
        请详细总结项目实施过程中所取得的各项主要成效，需结合具体数据和事实进行阐述。
        同时，提炼出项目在政策执行、资金管理、部门协同、服务优化等方面可供其他地区或类似项目借鉴的成功经验和有效做法
      keywords:
        - "效果与成效"
        - "实施方案"
        - "成功案例"
    
    - title: "四、存在的问题和原因分析"
      key: "problems"
      prompt_template: |
        请根据调研（如问卷调查、访谈）和数据分析，客观、准确地指出项目在实施过程中存在的主要问题。
        对于每个识别出的问题，都应深入剖析其产生的内外部原因
      keywords:
        - "风险与挑战"
        - "问题分析"
        - "原因调查"
    
    - title: "五、改进建议"
      key: "suggestions"
      prompt_template: |
        针对在'存在的问题和原因分析'部分指出的各项主要问题，请逐条提出具体的、有针对性的、可操作的改进建议。
        建议应明确改进方向、责任主体和预期效果
      keywords:
        - "改进措施"
        - "最佳实践"
        - "政策建议"

# =============================================================================
# 研究方向配置 - 用于综合研究Action
# =============================================================================
research_directions:
  # 网络研究增强查询模板
  enhancement_queries:
    - "最佳实践案例和成功经验"
    - "常见问题和风险因素"
    - "绩效评价指标和评价方法"
    - "相关的政策法规和标准规范"
  
  # 分解研究问题的维度
  decomposition_dimensions:
    - "决策维度分析"
    - "过程维度分析" 
    - "产出维度分析"
    - "效益维度分析"
  
  # 证据收集类别
  evidence_categories:
    - category: "项目基本信息"
      keywords: ["项目名称", "项目背景", "主要目标"]
    - category: "资金预算"
      keywords: ["预算金额", "资金来源", "支出明细"]
    - category: "实施内容"
      keywords: ["实施方案", "技术措施", "管理流程"]
    - category: "绩效指标"
      keywords: ["评价指标", "成果产出", "效益分析"]

  # 默认备用关键词（当LLM生成失败时使用）
  fallback_keywords:
    - category: "项目基本信息"
      keywords: ["项目名称", "项目背景", "主要目标"]
    - category: "资金预算"
      keywords: ["预算金额", "资金来源", "支出明细"]
    - category: "实施内容"
      keywords: ["实施方案", "技术措施", "管理流程"]
    - category: "绩效指标"
      keywords: ["评价指标", "成果产出", "效益分析"]

  # 证据摘要关键词映射（用于智能提取检索指导）
  evidence_keyword_mapping:
    预算资金数据:
      keywords: ["预算", "资金", "金额", "支出", "拨款"]
    目标指标设定:
      keywords: ["目标", "指标", "计划", "预期", "设定"]
    实施管理措施:
      keywords: ["实施", "管理", "措施", "方案", "流程"]
    实施效果数据:
      keywords: ["效果", "成果", "成效", "数据", "统计"]

  # Architect设计查询模板
  design_queries:
    - "报告结构 章节划分 目录大纲"
    - "关键指标 评价指标 绩效指标"
    - "数据分析 技术方案 实施方法"
    - "风险挑战 问题建议 解决方案"

# =============================================================================
# 评价标准配置 - 用于写作专家评价和打分
# =============================================================================
evaluation_standards:
  # 评价等级定义
  score_levels:
    优秀:
      min: 90
      max: 100
      description: "项目实施非常成功，各项指标均达到或超过预期"
    良好:
      min: 80
      max: 89
      description: "项目实施比较成功，主要指标达到预期"
    一般:
      min: 70
      max: 79
      description: "项目基本完成，但部分指标有待改进"
    及格:
      min: 60
      max: 69
      description: "项目勉强完成，存在较多问题"
    较差:
      min: 0
      max: 59
      description: "项目实施效果不佳，需要重大改进"
  
  # 四个维度权重配置
  dimension_weights:
    决策: 20  # 决策维度权重
    过程: 25  # 过程维度权重
    产出: 30  # 产出维度权重
    效益: 25  # 效益维度权重
  
  # 一级指标定义（用于验证指标结构）
  level1_indicators:
    - "决策"
    - "过程" 
    - "产出"
    - "效益"

# =============================================================================
# 提示词配置 - 架构师专用提示词模板
# =============================================================================
prompts:
  # 架构师基础系统提示词
  architect_base_system: |
    你是绩效评价报告的架构师。你的目标是：
    1. 深入分析研究简报，提取项目核心信息
    2. 基于标准绩效评价框架设计报告结构
    3. 构建科学的指标体系，确保评价的全面性和准确性
  
  # 项目信息提取提示词
  project_info_extraction: |
    你是绩效评价报告的架构师。请从以下研究简报中提取项目的核心信息，用于后续基于标准模板的报告结构设计。
    
    研究简报：
    {research_brief}
    
    请返回JSON格式，包含以下字段：
    1. project_name: 项目全称
    2. project_type: 项目类型（如：财政支出项目、专项资金项目等）
    3. budget_amount: 项目预算金额（如果有）
    4. implementation_period: 实施期间
    5. target_beneficiaries: 主要受益对象
    6. main_objectives: 主要目标（列表形式）
    7. key_activities: 主要活动内容（列表形式）
    8. performance_focus: 绩效重点关注领域（如：经济效益、社会效益、生态效益等）
    
    要求：
    - 信息要准确、完整
    - 如果某些信息不明确，标注为"待补充"
    - 重点关注与绩效评价相关的信息

  # RAG关键词生成提示词
  rag_keywords_generation: |
    你是架构师的RAG检索助手。基于以下项目信息，生成用于检索向量知识库的关键词组。
    
    项目信息：
    {project_info}
    
    请生成6个类别的检索关键词，每个类别包含3-5个具体的检索词：
    
    返回JSON格式：
    [
      {{
        "category": "项目背景与目标",
        "keywords": ["项目立项背景", "主要目标", "预期成果"]
      }},
      {{
        "category": "资金与预算",
        "keywords": ["预算总额", "资金来源", "资金分配"]
      }},
      {{
        "category": "实施方案",
        "keywords": ["实施步骤", "技术方案", "管理措施"]
      }},
      {{
        "category": "效果与成效",
        "keywords": ["实施效果", "产出指标", "效益分析"]
      }},
      {{
        "category": "政策依据",
        "keywords": ["政策文件", "法规依据", "标准规范"]
      }},
      {{
        "category": "风险与挑战",
        "keywords": ["存在问题", "风险因素", "改进建议"]
      }}
    ]
    
    要求：关键词要具体、准确，能在{project_name}相关资料中找到对应信息。

  # 章节提示词生成模板
  section_prompt_generation: |
    针对{project_name}，{base_prompt}
    
    ### 📋 具体写作指导与检索要求：
    
    {rag_instructions}
    
    ### 🔍 RAG检索策略：
    写作时请严格按照以下步骤进行：
    1. 首先检索上述关键信息项，获取具体数据和事实
    2. 基于检索到的真实信息进行分析和论述
    3. 避免泛泛而谈，确保每个论点都有具体的数据支撑
    4. 如果某项信息检索不到，明确标注"信息待补充"
    
    ### 📊 质量要求：
    - 数据准确：所有数字、时间、名称必须来自检索到的原始资料
    - 逻辑清晰：按照检索指导的顺序组织内容结构
    - 深度分析：不仅要列出事实，还要分析原因和影响

  # 指标体系设计提示词
  metrics_design: |
    你是绩效评价指标体系的架构师。请基于以下项目信息，设计一套完整的绩效评价指标体系。
    
    项目信息：
    {project_info}
    
    指标体系设计要求：
    1. 一级指标权重分配：决策(15分)、过程(25分)、产出(35分)、效益(25分)
    2. 每个一级指标下设置2-3个具体指标
    3. 每个指标必须选择一种评价类型，共6种可选：
       - "要素符合度计分": 根据符合的要素数量计分
       - "公式计算得分": 通过数学公式计算得分  
       - "条件判断得分": 根据是否满足条件计分
       - "定性与定量结合": 综合定性和定量评价
       - "递减扣分机制": 从满分开始根据问题扣分
       - "李克特量表法": 通过满意度调查计分
    
    请返回JSON格式，每个指标包含：
    - metric_id: 唯一标识（英文）
    - name: 指标名称（中文）
    - category: 指标分类
    - 一级指标: "决策"/"过程"/"产出"/"效益"
    - 二级指标: 具体的二级指标名称
    - 三级指标: 具体的三级指标名称
    - 分值: 该指标权重分值（与一级指标权重匹配）
    - evaluation_type: 评价类型（必须选择上述6种之一）
    - evaluation_points: 具体评价要点（数组格式，如["①立项符合法规","②符合规划"]）
    - scoring_method: 详细计分方式（如"具备一个要素得20%分值"）
    - 评分过程: Writer执行评价的具体指导
    
    ⚠️ 重要格式要求：
    - 所有字段名必须使用英文或中文，不能混用
    - scoring_method字段必须一致，不能使用"评分方法"或"scoring方法"
    - 确保JSON格式完全正确，所有字段都有值
    
    请为{project_name}（{project_type}）设计8-12个指标，确保：
    - 决策类指标总分值=15分
    - 过程类指标总分值=25分  
    - 产出类指标总分值=35分
    - 效益类指标总分值=25分
    - 每个指标都有明确的评价类型和详细评价要点

# =============================================================================
# 评价类型定义 - 6种标准化评价类型
# =============================================================================
evaluation_types:
  要素符合度计分:
    description: "根据各项要素的符合情况进行计分"
    scoring_guidance: |
      要素符合度计分计算步骤：
      1. 从事实中识别符合的要素（如"符合评价要点①②"）
      2. 从规则中提取每个要素的分值
      3. 将符合要素的分值相加得到最终得分
      
      示例：事实"符合①②，不符合③"，规则"①②各30%，③40%"
      计算：30+30+0=60分
    opinion_requirements: |
      - 必须包含具体的法规引用、文件名称等详实内容
      - 明确列出每个评价要点的符合/不符合情况
      - 使用分号分隔各要点的评价
      - 不得包含任何最终得分或结论性语句

  公式计算得分:
    description: "通过特定公式计算得出分数"
    scoring_guidance: |
      公式计算得分步骤：
      1. 从规则中找到计算公式
      2. 从事实中提取数值
      3. 代入公式计算，结果换算到100分制
      
      示例：预算执行率=实际支出/预算金额×100%
      实际支出800万，预算1000万
      计算：800/1000×100%=80%，得80分
    opinion_requirements: |
      - 必须列出具体的计算数据和来源
      - 展示完整的计算公式和计算过程
      - 如有多年数据，需计算加权平均值
      - 百分比保留两位小数
      - 不得包含任何最终得分或结论性语句

  条件判断得分:
    description: "根据是否满足特定条件来计分"
    scoring_guidance: |
      条件判断得分步骤：
      1. 识别事实满足的条件档次
      2. 给予该档次对应的分数
      
      示例：条件"项目有完整预算"，事实"项目编制了详细预算"
      判断：满足条件，得100分
    opinion_requirements: |
      - 明确说明每个条件的满足/不满足情况
      - 提供具体的证据材料或事实依据
      - 对于不满足的条件，说明具体缺失什么
      - 不得包含任何最终得分或结论性语句

  定性与定量结合:
    description: "结合定性描述和定量数据进行评价"
    scoring_guidance: |
      定性与定量结合步骤：
      1. 分别计算定量和定性部分分数
      2. 按权重合并分数
      
      示例：定量部分（60%权重）：完成率90%，得90分
      定性部分（40%权重）：质量优秀，得95分
      综合得分：90×0.6+95×0.4=92分
    opinion_requirements: |
      - 定量部分：列出具体数据、百分比、金额等
      - 定性部分：描述实地调研、访谈等发现的情况
      - 两部分要有机结合，不能割裂
      - 对于部分达标的情况，明确扣分比例
      - 不得包含任何最终得分或结论性语句

  递减扣分机制:
    description: "从满分开始根据问题情况进行扣分"
    scoring_guidance: |
      递减扣分机制步骤：
      1. 从满分开始
      2. 根据问题数量扣分
      3. 计算最终剩余分数
      
      示例：满分100分，每个问题扣10分
      发现3个问题，扣30分
      最终得分：100-30=70分
    opinion_requirements: |
      - 列出发现的每个问题及具体表现
      - 说明每类问题的扣分标准
      - 问题要具体到时间、地点、责任主体
      - 不得包含任何最终得分或结论性语句

  李克特量表法:
    description: "通过调查问卷和统计分析计算满意度"
    scoring_guidance: |
      李克特量表法步骤：
      1. 根据满意度百分比对应分数档次
      2. 或直接将满意度百分比作为得分
      
      示例：满意度调查结果92.8%
      90%以上为优秀，得满分
      最终得分：100分
    opinion_requirements: |
      - 说明调查方法和样本量
      - 列出各满意度等级的具体人数
      - 展示满意度计算公式和过程
      - 满意度百分比保留两位小数
      - 不得包含任何最终得分或结论性语句

# =============================================================================
# 章节特定配置 - 替代硬编码的条件判断逻辑
# =============================================================================
section_configurations:
  # 🎯 章节配置：通过section key自动映射，不再需要硬编码条件判断
  overview:  # 项目概述
    title_keywords: ["项目概述", "概述"]  # 用于自动匹配章节标题
    keywords: ["项目背景与目标", "资金与预算", "实施方案", "效果与成效"]
    rag_instructions: |
      **1. 项目立项背景及目的**
         - 检索关键词：项目背景与目标相关信息
         - 重点查找：政策文件引用、立项依据、目标设定
         
      **2. 资金投入和使用情况**
         - 检索关键词：资金与预算相关信息
         - 重点查找：预算总额、资金来源、分配明细、执行进度
         
      **3. 项目组织管理**
         - 检索关键词：实施方案相关信息
         - 重点查找：管理机构、职责分工、流程制度
         
      **4. 项目绩效目标**
         - 检索关键词：效果与成效相关信息
         - 重点查找：绩效目标表、指标设定、预期成果（务必以表格形式展示）

  conclusion:  # 综合绩效评价结论
    title_keywords: ["综合绩效评价结论", "评价结论", "绩效结论"]
    keywords: ["效果与成效", "评价指标", "绩效得分"]
    rag_instructions: |
      **决策、过程、产出、效益四个维度分析**
         - 检索关键词：效果与成效相关信息
         - 重点查找：各项指标完成情况、评分结果、综合得分
         - 必须输出：指标得分情况表（一级指标、分值、得分、得分率）

  achievements:  # 主要成效及经验
    title_keywords: ["主要成效及经验", "成效", "经验"]
    keywords: ["效果与成效", "实施方案", "成功案例"]
    rag_instructions: |
      **具体成效数据**
         - 检索关键词：效果与成效相关信息
         - 重点查找：量化成果数据、受益人群统计、效果对比
         
      **成功经验总结**
         - 检索关键词：实施方案相关信息
         - 重点查找：创新做法、管理经验、技术亮点

  problems:  # 存在的问题和原因分析
    title_keywords: ["存在的问题和原因分析", "问题", "原因分析"]
    keywords: ["风险与挑战", "问题分析", "原因调查"]
    rag_instructions: |
      **问题识别**
         - 检索关键词：风险与挑战相关信息
         - 重点查找：调研发现的问题、数据反映的不足、反馈意见
         
      **原因深度分析**
         - 检索关键词：政策执行、管理制度、技术条件、外部环境
         - 重点查找：问题产生的内在机制和外部因素

  suggestions:  # 改进建议
    title_keywords: ["改进建议", "建议"]
    keywords: ["改进措施", "最佳实践", "政策建议"]
    rag_instructions: |
      **针对性建议**
         - 基于前述问题分析，检索关键词：风险与挑战相关信息
         - 重点查找：改进措施、政策建议、技术优化方案
         
      **可操作性验证**
         - 检索关键词：成功案例、最佳实践、政策支持
         - 重点查找：类似项目的改进经验、政策可行性分析

  # 🎯 通用章节配置 - 作为备用
  general:
    title_keywords: ["其他", "通用"]
    keywords: ["项目相关信息"]
    rag_instructions: |
      **通用检索指导**
         - 优先检索：项目相关的具体数据、政策文件、实施效果
         - 重点关注：数量化指标、时间节点、责任主体、具体措施

# =============================================================================
# 智能检索配置 - 用于智能检索服务
# =============================================================================
intelligent_search:
  # 查询意图分析配置
  query_intent_mapping:
    performance: ["绩效评价", "指标体系", "效益", "风险"]
    reasoning: ["关系推理", "关联", "因果", "影响"]
    exploration: ["如何", "探索", "详细", "深入"]
    general: ["其他"]
  
  # 检索模式权重配置
  search_mode_weights:
    vector: 0.6      # 向量检索权重
    knowledge_graph: 0.4  # 知识图谱权重