# =============================================================================
# 项目配置文件 - project01.yaml
# 项目信息配置化，消除LLM提取的不确定性
# =============================================================================

# 项目基本信息（对应architect_action.py中的8个字段）
project_info:
  project_name: "陶丘市睢阳区李口镇人民政府睢阳区李口镇农村公益事业财政奖补项目(温堂村、贾杨楼村)"
  project_type: "公益事业财政奖补项目"
  province: "河南省"
  city: "商丘市"
  county: "睢阳区"
  project_description: "项目立项以提升农村居民生活质量、促进城乡基本公共服务均等化为核心目标，重点支持村级道路硬化、公共照明配套等公益性基础设施建设。项目覆盖李口镇下辖贾杨楼村、温堂村，致力于解决群众反映强烈的出行难问题，增强村民获得感与满意度"


# 文件路径配置
file_paths:
  uploads_dir: "workspace/project01/uploads"
  documents:
    - "workspace/project01/uploads/项目移交表.md"
    - "workspace/project01/uploads/三重一大事项报告单，财政审核表.md"
    - "workspace/project01/uploads/财政决算评审.md"
    - "workspace/project01/uploads/财政预算评审.md"
    - "workspace/project01/uploads/李口镇4个村申请.md"
    - "workspace/project01/uploads/项目资金支付凭证.md"
    - "workspace/project01/uploads/项目造价表.md"
    - "workspace/project01/uploads/项目竣工资料.md"
    - "workspace/project01/uploads/项目建立资料监理日志.md"
    - "workspace/project01/uploads/中标合同验收.md"


# 工作区配置
workspace:
  project_id: "project01"
  base_path: "workspace/project01"
  vector_storage_path: "workspace/project01/vector_storage"

# 用户消息配置（用于模拟chainlit输入）
user_message_sop1: "请基于本项目资料，设计完整可评分的绩效指标体系，并完成各个指标的评价意见与评分。"
user_message_sop2: "请基于已完成的指标体系表、撰写报告章节内容，撰写本项目的绩效评价报告。"
user_message_product_manager: "在绩效报告编写前期,需要一份深度的调查研究报告,为后续指标评价和章节编写提供参考。"

# 独立入口智能体用户消息配置
user_message_architect_content: "请基于研究简报设计报告章节结构，生成包含写作指导和事实引用要求的完整结构。"
user_message_section_writer: "请基于已生成的报告结构，撰写各章节内容并聚合为最终报告。"